version: '3'
services:
  crackable:
    build: .
    environment:
      - FLAG=TCF2024{HALOOooOOğŸ‘‹_I'm_EmuğŸ¤©_OtoriğŸ¤—_EmuğŸ˜_is_meaningğŸ˜‹_smileğŸ˜_wonderhoyyyyâœ¨ğŸ‰ğŸ§¨ğŸğŸ¢}
    ports:
      - "42069:42069"
    restart: always